### ISSUE TITLE
Token Authentication

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#221] opened 2015-03-03 20:03 UTC
This authentication method allows us to easily timeout people's access to the backend since the token will have an expiry date. Also it will fix #202, since tokens generation is dependent from the browser and IP the user is using. This resource (http://blog.miguelgrinberg.com/post/restful-authentication-with-flask) may be useful for implementing it.

**Comment by lenglund** [comment] 2016-04-11 19:59
Duplicate of #249.

**Comment by lenglund** [comment] 2016-09-08 16:43
Closing due to duplication.

**Closed by lenglund** 2016-09-08 16:43 UTC
Labels: developer suggestion, duplicate, enhancement, medium priority
